### ISSUE TITLE
Suggestion for a better licence

### ISSUE THREAD

**Issue by smoia** [Cristina-Tobias/clustintime#1]
Hey @Cristina-Tobias !
Nice to see you're creating a toolbox out of your work!

May I suggest to change the associated licence, at least from LGPL v2 to LGPL v3, or even a change to Apache2?
Unless you are using code from other libraries that require you to have a LGPL v2 .1
You can find all differences between licences [here](https://choosealicense.com/licenses/).
The difference between (L)GPL2 and (L)GPL3 is explained [here](https://www.gnu.org/licenses/rms-why-gplv3.en.html).

Have a good time developing!

**Comment by Cristina-Tobias** [comment]
Thank you!!! I will change it now
